winget uninstall Microsoft.549981C3F5F10_8wekyb3d8bbwe  
winget uninstall Microsoft.Getstarted_8wekyb3d8bbwe  
winget uninstall Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe  
winget uninstall Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe  
winget uninstall Microsoft.Office.OneNote_8wekyb3d8bbwe  
winget uninstall Microsoft.People_8wekyb3d8bbwe  
winget uninstall Microsoft.ScreenSketch_8wekyb3d8bbwe  
winget uninstall Microsoft.SkypeApp_kzf8qxf38zg5c 
winget uninstall Microsoft.Wallet_8wekyb3d8bbwe  
winget uninstall Microsoft.WindowsMaps_8wekyb3d8bbwe                                          
winget uninstall microsoft.windowscommunicationsapps_8wekyb3d8bbwe
